### ISSUE TITLE
Doesn't work on linux/ubuntu

### ISSUE THREAD

**Issue by mrcrowl** [mrcrowl/vscode-easy-less#21]
There have been two reports of easy-less extension not working on linux:

@kobyo - 2017-05-02 [Ubuntu 16.10]
@Eric Dubé - 2016-11-14 [unknown version/flavor]

**Comment by mrcrowl** [comment]
Here's a quick screen capture of my experience of using easy-less in vscode on ubuntu 16.10.

I made a simple .less file, hit Ctrl+S and the .css file is created:
![easy-less](https://cloud.githubusercontent.com/assets/1796256/25772039/a9c29492-32b5-11e7-97a9-c2d06b97ce4c.gif)

**Comment by zaszlo** [comment]
I'm having Ubuntu 16.10 and found this issue by searching for why this extension is not working. I mean I have a less file, save it nothing happens, no file is generated. Tried to delete the old css, tried to start just a plain new less and save that... extension doesn't seem to be triggered, no message is shown as hinted in the extension description and eventually nothing happens when I save my `.less` file.

**Comment by zaszlo** [comment]
hmm.. fixed it by removing my "less.compile" section from settings.json and then readded it. Now it started to just work on save as expected. :D

**Comment by zaszlo** [comment]
Its not that simple, sometimes it works, then it does not.. its unreliable for me, wasted a few hours with it.

**Comment by zaszlo** [comment]
I'm not sure if it is an Ubuntu issue, I got it under windows now as well. For me I guess the problem stands in the fact that my less file is pretty big, it takes more than a minute to compile it and it is very frustrating that there is no process monitor / status bar message showing that the compilation is taking place, only after it is finished there is a message that it has been compiled in x sec... shown for like 2 sec after waiting for it for a minute or so. 

For the process to be easier to follow I usually delete the old css and map files so that when it finishes I can see that the new files got there. Automating this deletion or renaming the old ones to .old to follow the compilation process would be a nice feature I think.
