### ISSUE TITLE
Is there a way I can trigger a Post Compilation event 

### ISSUE THREAD

**Issue by Sivakumaresan** [mrcrowl/vscode-easy-less#41]
I have a requirement to copy the output (css files) to multiple destination paths. As we have today I can only specify one "out" path, thinking if there is a post build script if I can run then I can do an XCOPY to multiple destination folders. Something like below,
`"less.compile": {
        "post-out": "xcopy-tool.exe"
    }`

**Comment by mrcrowl** [comment]
At a stretch, you _might_ be able to use multiple `main` directives at the top of a less file, so that EasyLESS will generate more than one output.

But the ability to run post-compilation events is a little outside the scope of what EasyLESS is meant for.  

Some alternatives would be a task runner like gulp/grunt/bash script/npm script etc.
