### ISSUE TITLE
How to compile only one of them?

### ISSUE THREAD

**Issue by percyho** [mrcrowl/vscode-easy-less#68]
I have two less files. How to compile only one of them?

**Comment by mrcrowl** [comment]
Hi there. Can you provide some more details on what you're wanting? Why do you want one file compiled and not the other? Is there any relationship between these files?

**Comment by percyho** [comment]
Hi, there, Because one file is imported into another file, so I don't want to compile them all

**Comment by percyho** [comment]
Hi there. Because one file is imported into another, I don't want to compile them.

**Comment by mrcrowl** [comment]
Okay. You can use the `// main: <some-filename.less>` directive for this. 

You put this comment at the top of the imported file. That tells EasyLESS which file to compile instead of the file itself. That way, whenever you save the imported file, the "main" file gets recompiled. 

More details on this in the [readme](https://github.com/mrcrowl/vscode-easy-less).
