### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by jhemesferreira** [mrcrowl/vscode-easy-less#76]
Since last week I am no longer able to compile my files. I don't have any warning. Anyone else with this problem?

**Comment by mrcrowl** [comment]
Hi, can you please provide an example Less snippet that no longer works? Or is it not working for any file?

**Comment by jhemesferreira** [comment]
Hi, thank you for your answer. It is not working for any file

**Comment by mrcrowl** [comment]
> Hi, thank you for your answer. It is not working for any file

How curious... can you please describe any steps that you have already taken to address this, so that I can exclude them: e.g. uninstall and reinstall of the extension, trying EasyLESS in a separate project, trying on a second computer etc. I currently cannot repro the issue based on the information given. 

Also, what OS? What version of VS Code? If Windows, are you using WSL or remote/ SSH connection?

**Comment by jhemesferreira** [comment]
We have already tried all those things that you describe, but no success. 
My OS is windows 10, and last version of vs code (1.53.2).

**Comment by mrcrowl** [comment]
Ok. Can you also please check the Extensions output in the Output pane for
any error messages?

For now, hopefully you can manually install a prior version from a VSIX on
the release page until I can spend more time investigating: e.g. 1.7.0
https://github.com/mrcrowl/vscode-easy-less/releases/tag/v1.7.0

**Comment by jhemesferreira** [comment]
thank you so much.
