### ISSUE TITLE
How to generate *.min.css from *.less?

### ISSUE THREAD

**Issue by arunn87** [mrcrowl/vscode-easy-less#86]
I couldn't find any documentation related to minified css file generation from LESS. Is it possible with this plugin? (something similar to https://github.com/madskristensen/LessCompiler LESS compiler for visual studio)

**Comment by mrcrowl** [comment]
The closest feature to this is the `compress` option, which minifies the css. However, this doesn't generate a separate `.min.cs` file, as this seemed redundant when the `.less` file is the source of truth.

If you really want this, then please submit a PR. Happy to coordinate on getting it released. But otherwise I won't be working on it.
